apiVersion: apps/v1
kind: Deployment
metadata:
  name: averageprint-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: averageprint
  template:
    metadata:
      labels:
        app: averageprint
    spec:
      containers:
      - name: averageprint
        image: golangtrainee/averageprint:latest  
